### PR TITLE
More comments on working examples

### PR DESCRIPTION
**Pull request by MathiasMehl**
I added some comments to the cases that I have made, that needed more comments to be understood. 
Some other of our cases still need a bit of documentation to be easily understood.

### CODE REVIEW

**Comment by NicEastvillage** [comment]
Could you make  list of lcgs programs missing descriptions and who created them?

**Comment by NicEastvillage** [comment]
I am currently working on more descriptions as well as converting the json formulas to ATL formulas.

**Comment by MathiasMehl** [comment]
Some more comments could be added to intrusion detection and public good game, I believe Asger wrote intrusion detection, and he and I collaborated on the first version of public good game. 
I am not sure if we need to document these, as they are quite small test cases, and we will probably mostly use the newer (and much larger) lcgs programs for testing.
I'll rewrite the json formulae for the mutex algorithms (fischer and peterson) to ATL.

**Review by GeneralDenmark — APPROVED** [review]
Looking good to me, small edit to Rock Paper Scissors in #106

**Comment by NicEastvillage** [comment]
Intrusion detection and matching pennies is exactly the same model (when the probability is removed), so I decided to delete one of them: Intrusion detection.

**Review by lars4509 — APPROVED** [review]
Looks good.

**Pull request merged**
