### PR TITLE
[ATL] Adds more formula term (And, Eventually, Invariant, ...)

### PR DESCRIPTION
**Pull request by NicEastvillage**
This PR adds the following terms to ATL formulas:
* True
* False
* And
* DespiteNext (and renames Next to EnforcedNext)
* EnforceEventually
* DespiteEventually
* EnforceInvariant
* DespiteInvariant

It should be easy to convince yourself that the edges and successor configurations are correct (It's just proving it, that is hard).

There are also some clean up like improving comments and replacing some u32 with usize.

### CODE REVIEW

**Comment by NicEastvillage** [comment]
Just realized we are missing True and False. Will do these later.

**Comment by NicEastvillage** [comment]
Done.

Bonus info: The formula `⟪0,1⟫(('1' ∨ ¬('2')) 𝑼 false)` is written like this in json:
```json
{
  "enforce until": {
    "players": [0,1],
    "pre": {
      "or": [
        {
          "proposition": 1
        },
        {
          "not": {
            "proposition": 2
          }
        }
      ]
    },
    "until": "false"
  }
}
```

**Review by cogitantium — APPROVED** [review]

**Comment by NicEastvillage** [comment]
Have renamed always to invariant

**Review by lars4509 — APPROVED** [review]
Looks good to me

**Pull request merged**
