### PR TITLE
Terminate when all have completed

### LINKED ISSUE #11: Missing termination condition
If all worker queues empty, the `distributed_certain_zero` will come to a stand still and never produce a result. The `TerminationDetection` function needs to be implemented as prescribed in Extended _Dependency Graphs and Efficient Distributed Fixed-Point Computation_

### PR DESCRIPTION
**Pull request by jenrik**
Implements a solution for terminating the algorithm once all queues empty and all worker goes idle. The solution is based on weight throwing as described in the article "Detecting termination of distributed computations by external agents" by Shing-Tsaan Huang, 1989

resolves #11

### CODE REVIEW

**Review by GeneralDenmark — APPROVED** [review]
Nice, LGTM :tada:

**Comment by jenrik** [comment]
I request we stall this pull request and #36 until we have discussed my idea of using vector clocks that I described on Discord

**Comment by jenrik** [comment]
I'm abandoning the vector clock idea for now, let's get this merged

**Comment by jenrik** [comment]
[Review Distributed Termination PR](https://trello.com/c/AcT2shma/68-review-distributed-termination-pr)

**Review by NicEastvillage — APPROVED** [review]
Looks interesting.
So correct me if I am wrong, the general idea is to give each task a weight, and whenever a task has subtasks, that weight i split to give each subtask some weight. And whenever a (sub)task is done, the weight is returned to the controller. Once the controller has all the weight again, then we are out of tasks. Correct?

**Comment by jenrik** [comment]
@NicEastvillage yes, that is more or less correct. You start out by having a weight of 1, and then that is subdivided every time a task produces more tasks. If a task doesn't produce any tasks then its weight is returned to the controller. The controller knows there is no more work in progress or pending once it have received a collective weight of 1

**Review by MathiasMehl — APPROVED** [review]

**Pull request merged**
