### PR TITLE
Criterion.rs benchmarking

### PR DESCRIPTION
**Pull request by cogitantium**

### CODE REVIEW

**Comment by cogitantium** [comment]
Missing proper configuration to access model_check main functions, related to second point in docs: https://bheisler.github.io/criterion.rs/book/user_guide/known_limitations.html

**Comment by cogitantium** [comment]
We should also have benchmarks for important internal functions, such as parsing LCGS

**Comment by cogitantium** [comment]
Now depends on #43

**Comment by cogitantium** [comment]
We've abandoned this approach for benchmarking our tool vs PRISM, instead using https://github.com/d702e20/bench-solver/.

This may become useful in future for micro benching internally for performance improvements.

**Comment by jenrik** [comment]
I think this is still worth keeping open for use in future development

**Comment by cogitantium** [comment]
Codebase adopted by #101, keep this closed until #101 is resolved.

**Pull request closed without merging**
